### ISSUE TITLE
changelog prepare should have a --force

### ISSUE THREAD

**Issue by mh-cbon** [mh-cbon/changelog#6]
The case is a program with mutliple pre releases,
now it wants to move on a new release gold,
its last commit was a pre release one since then nothing was changed,

when run `changelog prepare`, cl won t prepare a new release in
the changelog file because no changes were found.

Add a --force argument to write the UNRELEASED version even though no changes were found.
Add a default changes saying so.
Let the user fill in the details (probably a summary of the multiple pre release change logs)

**Comment by solvingJ** [comment]
I don't know if my issue is exactly the same as the one reported here.  I get the same error "no changes were found" but there are no pre-releases.  I did one pre-release and then finalized it.  Then I did several new commits.  I double checked and I also can't do changelog finalize because "No UNRELEASED version into this changelog".

**Comment by mh-cbon** [comment]
hi,

"no changes were found"
means the vcs do not have commit in it, usually.

"No UNRELEASED version into this changelog"
means the next release does not exists in the CL.

______
to summarize
1. git init 
2. touch readme ...
3. git add -A && git commit -m

at that moment the CL can init
4. cl init
then commit your stuff as usual.

Then prepare for a release,
5. cl prepare

that will create a new release with as "UNRELEASED", which you can update and fix

Edited or not, finalize will select that version and promote it.

__ 

hth, sorry for all the misses you spotted, they are worthy indeed.

**Comment by solvingJ** [comment]
I definitely started with the empty repo problem, but saw your issue that a Commit shouldn't be required (but is today).  However, then I did an initial git commit, and was able to do changelog init successfully.  

So, I definitely have commits, but now can't get changelog to detect further changes.  I could be missing something, but there's not a lot to do wrong.  I added a file called "detectme.txt", committed it, and pushed it, and you can see my commit history and CHANGELOG here:

https://github.com/solvingJ/go-github-release-test

If you have the time, you can simply clone my repo, and in theory, running changelog prepare should detect the in-processed commit for detectme.txt on your machine, and proceed.  Maybe you can find the issue.

**Comment by mh-cbon** [comment]
I think you tried to bump patch, it failed, and you are in a dirty status,
where some thing are advanced to 0.0.1, and some others did not.

my guess, this failed ` emd gen -in README.e.md > README.md`,
leaving you with a changelog at 0.0.1, but no such version in git tags.

In such case i d simply manually rename (without commit) 
to `UNRELEASED` the release name in the change.log file,
https://github.com/solvingJ/go-github-release-test/blob/master/change.log#L2

then If you gump patch again, should produce the same error, same dirty status.

To fix it, either create a readme file,
or comment / remove those lines about the readme file (comments starts with a #),
the gump patch should work that time.

**Comment by mh-cbon** [comment]
Note: in your next attempt you should fail again at
https://github.com/solvingJ/go-github-release-test/blob/master/.version.sh#L19

Which won t matter this time as the error happen at POSTVERSION, so the git tag is created ,the changelog is updated, everything was pushed, the bump will keep working.

At contrary to your current situation where it happened at PREVERSION, which is not so good.

You  could move the change.log / readme.md file updates to POSTVERSION, but i don t do that so their commits are into their respective version, its very little adjustment, very subjective.
